### ISSUE TITLE
Seems there's an issue?

### ISSUE THREAD

**Issue by CaidenM** [CBenni/logviewer#10]
root@server:~/logviewer# node index.js
error: uncaughtException: Unexpected token ; date=Sat Jan 06 2018 16:23:49 GMT+0100 (CET), pid=14716, uid=0, gid=0, cwd=/root/logviewer, execPath=/usr/bin/node, version=v8.9.4, argv=[/usr/bin/node, /root/logviewer/index.js], rss=57991168, heapTotal=35065856, heapUsed=24145176, external=1261720, loadavg=[0.3583984375, 0.44873046875, 0.40087890625], uptime=259531
/root/logviewer/bot.js:343
                let channelObj = {name: data[PARAM].slice(1), id: data[TAGS]["room-id"];

I have looked at other issues, and I haven't saw this come up yet maybe Cbenni can give some insight? Not looking for support or anything :)

**Comment by CBenni** [comment]
The most current commits on this repo are abandoned WIPs, use the latest non-WIP commit instead

**Comment by CaidenM** [comment]
Thanks for the quick reply very much appreciated

awesome app btw!
