### ISSUE TITLE
Badges json how did you get ?

### ISSUE THREAD

**Issue by GuimDev** [CBenni/logviewer#14]
Hi @CBenni ,

https://github.com/CBenni/logviewer/blob/d7cf0b524851e9db6be2084922c84a6d9282f7e4/index.js#L881

How did you get this json ? Because Twitch API doesn't give all badges

(And : `https://cbenni.com/api/badges/${channel}` is offline)

Thanks you,  
Guimdev.

**Comment by Decicus** [comment]
There are API endpoints for global and channel badges: https://discuss.dev.twitch.tv/t/beta-badge-api/6388

**Comment by CBenni** [comment]
I use exactly that API. Keep in mind it is deprecated and subject to removal or change at any point in time without notification, which is why I abstract it away. 
I believe your question is solved, so I am closing this.
