### ISSUE TITLE
Save button & footer bar are overlapping settings

### ISSUE THREAD

**Issue by PowerJax** [CBenni/logviewer#4]
When using Safari the footer bar and save button on the settings page are overlapping the settings.

**OS: MacOS Sierra 10.12.5**
**Browser: Safari 10.1.1 (12603.2.4)**
**Issue only occurs when using Safari**
**![Example](https://user-images.githubusercontent.com/25401745/28641080-2e27365c-724e-11e7-99ef-5b44f0a5b6a1.png)**

**Comment by CBenni** [comment]
Thanks for the report. Heres how to fix: use chrome.

Safari is really awful about basically everything and I cant test it on my end either :x

**Comment by PowerJax** [comment]
I normally don't use safari, but I came across it yesterday so I just wanted to let you know :)
